### ISSUE TITLE
Environment "leaks" into snaps under test

### ISSUE THREAD

**Issue by AlanGriffiths** [canonical/checkbox-mir#6]
This is particularly important for classic snaps (such as egmde - which crashes on Ctrl-Alt-Shift-T because of libc troubles)

**Comment by Saviq** [comment]
This is now pruned:

https://github.com/canonical/mir-ci/blob/2e72fd7036044afa882f9187c30023dc16bf6e92/mir-ci/mir_ci/program/program.py#L115-L122
